# {CENUM_START_OF_MESSAGE}{sep}{CENUM_CLIENT_CONFIG}{sep}{self.nickname}{sep}{self.s.getsockname()}


CENUM_START_OF_MESSAGE = "!@#*()"
sep = "<SEP>" 
MSG_TYPE = 1

# client sends this message at the start of connection
CENUM_CLIENT_CONFIG_len = 4
CENUM_CLIENT_CONFIG = "CLIENTCONFIG"
CENUM_CLIENT_CONFIG_NICKNAME = 2
CENUM_CLIENT_CONFIG_SOCKNAME = 3

# client sends message to an individual with this message
CENUM_INDIVIDUALMESSAGE_len = 5
CENUM_INDIVIDUALMESSAGE = "INDIVIDUAL_MESSAGE"
CENUM_INDIVIDUALMESSAGE_SENDER_SOCKET = 2
CENUM_INDIVIDUALMESSAGE_RECEIVER_SOCKET = 3
CENUM_INDIVIDUALMESSAGE_MESSAGE = 4


# client receives individual message
CENUM_RCV_INDIVIDUALMESSAGE_len = 4
CENUM_RCV_INDIVIDUALMESSAGE = "RECEIVE_INDIVIDUAL_MESSAGE"
CENUM_RCV_INDIVIDUALMESSAGE_SENDER_SOCKET = 2
CENUM_RCV_INDIVIDUALMESSAGE_MESSAGE = 3

# server sends list of users
SENUM_USERLIST_len = 3
SENUM_USERLIST = "USERLIST"
SENUM_USERLIST_USERS = 2

# client creates a group
CENUM_CREATEGROUP_len = 3
CENUM_CREATEGROUP = "CREATEGROUP"
CENUM_CREATEGROUP_CREATORNICKSOCK = 2

# server lets people know the group is created, with the generated group name (most likely ID) appended. everyone gets this message
SENUM_GROUPCREATED_len = 4
SENUM_GROUPCREATED = "NEWGROUP"
SENUM_GROUPCREATED_CREATORNICKSOCK = 2
SENUM_GROUPCREATED_GROUPNAME = 3

# client lets server know that client wants to join a group
CENUM_JOINGROUP_len = 5
CENUM_JOINGROUP = "JOINGROUP"
CENUM_JOINGROUP_CREATORNICKSOCK = 2
CENUM_JOINGROUP_GROUPNAME = 3
CENUM_JOINGROUP_JOINERNICKSOCK = 4

# server lets everyone know that a new client joined (by sending the updated list of participants)
SENUM_SOMEONEJOINEDGROUP_len = 3
SENUM_SOMEONEJOINEDGROUP = "SOMEONE_JOINED_THE_GROUP"
SENUM_SOMEONEJOINEDGROUP_GROUPOBJECTWITHLISTOFPARTICIPANTS = 2

# client sends a group message (server relays this message)
CENUM_GROUPMESSAGE_len = 5
CENUM_GROUPMESSAGE = "GROUP_MESSAGE"
CENUM_GROUPMESSAGE_GROUPNAME = 2
CENUM_GROUPMESSAGE_SENDERNICKSOCK = 3
CENUM_GROUPMESSAGE_MESSAGE = 4

# client exists a group
CENUM_LEAVEGROUP_len = 4
CENUM_LEAVEGROUP = "LEAVEGROUP"
CENUM_LEAVEGROUP_GROUPNAME = 2
CENUM_LEAVEGROUP_LEAVINGNICKSOCK = 3

# server notifies removed group
SENUM_REMOVEDGROUP = "REMOVEDGROUP"
SENUM_REMOVEDGROUP_GROUPNAME = 2
