# {CENUM_START_OF_MESSAGE}{sep}{CENUM_CLIENT_CONFIG}{sep}{self.nickname}{sep}{self.s.getsockname()}


sep = "<SEP>" 
CENUM_CLIENT_CONFIG = "CLIENTCONFIG"
CENUM_START_OF_MESSAGE = "!@#*()"
CENUM_CLIENT_CONFIG_NICKNAME = 2
CENUM_CLIENT_CONFIG_SOCKNAME = 3